layout: sidebar
style: light
repository: nelsonmestevao/dev

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  linkedin: nelsonmestevao
  twitter: nelsonmestevao

topics:
  - name: Haskell
    web_url: https://github.com/topics/haskell
    image_url: https://raw.githubusercontent.com/github/explore/a99873de88db54b274184fed1eebdb01da4dd92b/topics/haskell/haskell.png

